CREATE TABLE task (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	priority INTEGER DEFAULT 0,
	userid INTEGER NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
